<a href="https://colab.research.google.com/github/aayalas/Python_para_Data_Science_Pandas/blob/main/Python_DS_PD_Selection_Forms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
import pandas as pd

In [53]:
'l1 l2 l3 l4'.split()

['l1', 'l2', 'l3', 'l4']

In [54]:
data = [(1, 2, 3, 4), 
        (5, 6, 7, 8), 
        (9, 10, 11, 12),
        (13, 14, 15, 16)]
df = pd.DataFrame(data, 'l1 l2 l3 l4'.split(), 'c1 c2 c3 c4'.split())
df

    c1  c2  c3  c4
l1   1   2   3   4
l2   5   6   7   8
l3   9  10  11  12
l4  13  14  15  16

In [55]:
df['c1']

l1     1
l2     5
l3     9
l4    13
Name: c1, dtype: int64

In [56]:
type(df['c1'])

pandas.core.series.Series

In [57]:
df[['c3','c1']]

    c3  c1
l1   3   1
l2   7   5
l3  11   9
l4  15  13

In [58]:
type(df[['c3','c1']])

pandas.core.frame.DataFrame

In [59]:
df

    c1  c2  c3  c4
l1   1   2   3   4
l2   5   6   7   8
l3   9  10  11  12
l4  13  14  15  16

In [60]:
df[1:3]

    c1  c2  c3  c4
l2   5   6   7   8
l3   9  10  11  12

In [61]:
df

    c1  c2  c3  c4
l1   1   2   3   4
l2   5   6   7   8
l3   9  10  11  12
l4  13  14  15  16

In [62]:
df[1:][['c3','c1']]

    c3  c1
l2   7   5
l3  11   9
l4  15  13

In [63]:
df

    c1  c2  c3  c4
l1   1   2   3   4
l2   5   6   7   8
l3   9  10  11  12
l4  13  14  15  16

In [70]:
df.loc['l3']

c1     9
c2    10
c3    11
c4    12
Name: l3, dtype: int64

In [69]:
df.loc[['l3', 'l2']]

    c1  c2  c3  c4
l3   9  10  11  12
l2   5   6   7   8

In [71]:
df

    c1  c2  c3  c4
l1   1   2   3   4
l2   5   6   7   8
l3   9  10  11  12
l4  13  14  15  16

In [72]:
df.loc['l1', 'c2']

2

In [73]:
df.iloc[0, 1]

2

In [74]:
df.loc[['l3', 'l1'], ['c4', 'c1']]

    c4  c1
l3  12   9
l1   4   1

In [75]:
df.iloc[[2,0], [3,0]]

    c4  c1
l3  12   9
l1   4   1